[package]
name = "aoc_2025_day_01"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "day_01"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
indoc = "2.0.7"
lazy_static = "1.5.0"
